server:
  adminMinThreads: 1
  adminMaxThreads: 64
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 9091

mongo:
  host: localhost
  port: 12345
  db: metadata
  dbCollection: counters
  
buffer:
  maximumSize: 100
  expireAfterWriteInSec: 10
  expireAfterAccessInSec: 10
  threshold: 5
